## hugo 設定檔教學： https://gohugo.io/overview/configuration/ & `hugo help`

### 網站資訊

# baseURL： （預設值： ""） 根的主機名或路徑
baseURL: https://bwaycer.github.io/about/
# title： （預設值： ""） 網站名稱
title: 關於我
# theme： （預設值： ""） 採用的樣式名稱


## 開發功能

# editor： （預設值： ""） 若有設置，開啟新內容時會使用此編輯器
#     edit new content with this editor, if provided
# log： （預設值： false） 是否啟用日誌
# logFile： （預設值： ""） 日誌路徑，若設定此值 `log` 自動啟用
# config： （預設值： "config.toml"） 設定檔路徑，允許 `toml`、`yaml`、`json` 等附檔名（在 `hugo new site` 時可透過 `-f, --format` 指定）
# disableLiveReload： （預設值： false） 是否禁用及時更新
#     https://gohugo.io/extras/livereload/
# noTimes： （預設值： false） 是否不同步文件修改（modification）時間


### 路徑規範

# contentDir： （預設值： "content"）
# dataDir： （預設值： "data"）
# defaultLayout： （預設值： "post"）
# layoutDir： （預設值： "layouts"）
# paginate： （預設值： 10）
#     http://gohugo.io/extras/pagination/
# paginatePath： （預設值： "page"）
# permalinks： 固定連接，自定義路由
#     見 https://gohugo.io/extras/permalinks/
# staticDir： （預設值： "static"）
# themesDir： （預設值： "themes"） theme to use (located by default in /themes/THEMENAME/)


### 路由

# publishDir： （預設值： "public"） filesystem path to write files to
# source： （預設值： ""） filesystem path to read files relative from
# watch： （預設值： true） watch filesystem for changes and recreate as needed
# uglyURLs： （預設值： false） 是否顯示副檔名
# disablePathToLower： （預設值： false） 是否網址維持原始名稱而非統一小寫


### 多國語系

# defaultContentLanguage： （預設值： "en"） 缺少翻譯時默認使用此語言的內容
# defaultContentLanguageInSubdir： （預設值： false）
#     是否默認語言的內容被放置於相對的子路徑下（如：`/en/`），此路徑將自動重定向
# enableMissingTranslationPlaceholders： （預設值： false） 缺少翻譯時使用佔位符（placeholder）替代默認值或者空值
# languageCode： （預設值： ""）
languageCode: zh-tw
# pygmentsCodeFencesGuessSyntax： （預設值： false） enables syntax guessing for code fences without specified language
# hasCJKLanguage： （預設值： false）
#     if true, auto-detect Chinese/Japanese/Korean Languages in the content.
#     (.Summary and .WordCount can work properly in CJKLanguage)


### 生成文檔

# buildDrafts： （預設值： false） 是否生成頁面時忽略草稿標記
# buildFuture： （預設值： false） include content with publishdate in the future
# buildExpired： （預設值： false） include content already expired
# relativeURLs： （預設值： false） 是否啟用相對路徑
#     enable this to make all relative URLs relative to content root.
#     Note that this does not affect absolute URLs.
# canonifyURLs： （預設值： false） if true, all relative URLs will be canonicalized using baseURL
#     ? 問號相關 https://seo.dns.com.tw/archives/1184
# enableEmoji： （預設值： false） 是否啟用表情符號
#     關於可用表情符號見： www.emoji-cheat-sheet.com
# pygmentsStyle： （預設值： "monokai"） 著色筆風格
#     見： https://gohugo.io/extras/highlighting/
#     關於高亮語法風格見： http://pygments.org/
# pygmentsUseClasses： （預設值： false） 是否使用類組名而非個別標籤的風格屬性來著色
# disableRSS： （預設值： false） 是否不生成 RSS 文件
# rssLimit： （預設值： 15） RSS 的最大顯示數量
# disableSitemap： （預設值： false） 是否不生成 Sitemap 文件
# sitemap： default sitemap configuration map
#    https://gohugo.io/templates/sitemap/
# enableGitInfo： （預設值： false） Enable GitInfo feature
# enableRobotsTXT： （預設值： false） 是否生成 robots.txt 文件
# disable404： （預設值： false） 是否不顯示 404 頁面


### 額外功能

# googleAnalytics： （預設值： ""） Google Analytics 追蹤識別碼


### 未知

# archetypeDir： （預設值： "archetypes"）
# defaultExtension： （預設值： "html"）
# disableKinds： （預設值： [ "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404" ]）
#     The below example will disable all page types and will render nothing.
#     ? 看不懂 http://www.ctolib.com/topics-111201.html
# disableHugoGeneratorInject： （預設值： false） Do not inject generator meta tag on homepage
# footnoteAnchorPrefix： （預設值： ""）
# footnoteReturnLinkContents： （預設值： ""）
# metaDataFormat： （預設值： "toml"） 有效值： "yaml", "toml", "json"
# newContentEditor： （預設值： ""）
# noChmod： （預設值： false） Don't sync permission mode of files
# pluralizeListTitles： （預設值： true） Pluralize titles in lists using inflect
# preserveTaxonomyNames： （預設值： true） 是否在分類名稱（taxonomy names）中保留特殊字符
#     （如：`Gérard Depardieu` vs `Gerard Depardieu`）
# stepAnalysis： （預設值： false） 是否顯示記憶體和程序的不同步驟的時序（timing of different steps of the program）
# verbose： （預設值： false） verbose output
# verboseLog： （預設值： false） verbose logging
...
